"""Render FIGURES.md (a browsable figure gallery) and PNG previews from figures/catalog.tsv.

    python scripts/build_figure_catalog.py

figures/catalog.tsv is the maintained list: one row per figure with what it shows, its statistics, the code
that makes it, caveats, and a `paper` column for recording which paper panel (if any) it becomes. The script
fails if a PDF under figures/ is missing from the catalog or a catalog row points at a missing file, so the
gallery cannot silently fall out of date.
"""
from __future__ import annotations

import csv
from collections import OrderedDict
from pathlib import Path

import fitz  # pymupdf

REPO = Path(__file__).resolve().parents[1]
CATALOG = REPO / "figures" / "catalog.tsv"
PREVIEWS = REPO / "figures" / "previews"
OUT = REPO / "FIGURES.md"
PREVIEW_WIDTH_PX = 1000


def load_catalog() -> list[dict]:
    with CATALOG.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f, delimiter="\t", quoting=csv.QUOTE_NONE))
    ids = [r["id"] for r in rows]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate ids in figures/catalog.tsv")
    return rows


def check_coverage(rows: list[dict]) -> None:
    listed = {r["file"] for r in rows}
    on_disk = {p.relative_to(REPO).as_posix() for p in (REPO / "figures").rglob("*.pdf")}
    missing_files = sorted(listed - on_disk)
    uncatalogued = sorted(on_disk - listed)
    if missing_files or uncatalogued:
        raise SystemExit("figures/catalog.tsv is out of date:\n"
                         + "".join(f"  listed but missing: {m}\n" for m in missing_files)
                         + "".join(f"  not in catalog:     {u}\n" for u in uncatalogued))


def preview_path(file: str) -> Path:
    p = Path(file)
    return PREVIEWS / f"{p.parent.name}__{p.stem}.png"


def render_preview(file: str) -> Path:
    out = preview_path(file)
    with fitz.open(REPO / file) as doc:
        page = doc[0]
        zoom = PREVIEW_WIDTH_PX / page.rect.width
        pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=False)
    out.parent.mkdir(parents=True, exist_ok=True)
    pix.save(out)
    return out


def md_cell(text: str) -> str:
    return text.replace("|", "\\|") if text else "—"


def build(rows: list[dict]) -> str:
    sections: "OrderedDict[str, list[dict]]" = OrderedDict()
    for r in rows:
        sections.setdefault(r["section"], []).append(r)

    lines = [
        "# Figure gallery",
        "",
        "Every figure the analysis produces, grouped by question. Generated by `scripts/build_figure_catalog.py` from",
        "[`figures/catalog.tsv`](figures/catalog.tsv) — edit the TSV (for example the `paper` column), then run",
        "`python run.py --steps catalog`.",
        "",
        "How to read the entries:",
        "",
        "* **RECONSTRUCTION** — the code that drew the original was lost; the script was rebuilt so that every value printed on the",
        "  original figure is reproduced (see [docs/PROVENANCE.md](docs/PROVENANCE.md)).",
        "* **Recovered script** — the original code was recovered from session records and runs unchanged apart from paths.",
        "* **Alternative exon** — present in some but not all of the gene's mapped transcripts (see the README).",
        "* p-values are uncorrected for multiple testing unless the entry says otherwise.",
        "* *Poster* marks panels used on the 2026 QCB SURP poster.",
        "",
        f"{len(rows)} figures:",
        "",
    ]
    for name, items in sections.items():
        anchor = name.lower().replace(" ", "-")
        anchor = "".join(ch for ch in anchor if ch.isalnum() or ch == "-")
        lines.append(f"* [{items[0]['id'][0]}. {name}](#{anchor}) — " + ", ".join(r["id"] for r in items))
    lines.append("")

    for name, items in sections.items():
        lines += [f"## {name}", ""]
        lines += ["| ID | Figure | Poster | Paper |", "|---|---|---|---|"]
        lines += [f"| [{r['id']}](#{r['id'].lower()}) | {md_cell(r['title'])} | {r['poster'] or ''} | {md_cell(r['paper']) if r['paper'] else ''} |"
                  for r in items]
        lines.append("")
        for r in items:
            preview = preview_path(r["file"]).relative_to(REPO).as_posix()
            lines += [
                f"### {r['id']}",
                "",
                f"**{r['title']}**",
                "",
                f'<a href="{r["file"]}"><img src="{preview}" width="720" alt="{r["id"]}: {r["title"]}"></a>',
                "",
                "| | |",
                "|---|---|",
                f"| File | [`{r['file']}`]({r['file']}) |",
                f"| Shows | {md_cell(r['shows'])} |",
                f"| Statistics | {md_cell(r['statistics'])} |",
                f"| Made by | `{r['made_by']}` |",
                f"| Notes | {md_cell(r['notes'])} |",
                f"| Poster | {r['poster'] or 'no'} |",
                f"| Paper | {md_cell(r['paper']) if r['paper'] else 'not decided'} |",
                "",
            ]
    return "\n".join(lines)


def main() -> None:
    rows = load_catalog()
    check_coverage(rows)
    keep = set()
    for r in rows:
        keep.add(render_preview(r["file"]))
    for stale in PREVIEWS.glob("*.png"):
        if stale not in keep:
            stale.unlink()
    OUT.write_text(build(rows) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} and {len(keep)} previews")


if __name__ == "__main__":
    main()
